spring:
  application:
    name: LibraryTracker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/changeMe}
    username: ${SPRING_DATASOURCE_USERNAME:changeMe}
    password: ${SPRING_DATASOURCE_PASSWORD:changeMe}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}

server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/app}
  port: ${SERVER_PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: ${HIBERNATE_SQL_LOG_LEVEL:info}
        orm:
          jdbc:
            bind: ${HIBERNATE_BIND_LOG_LEVEL:info}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_OPENAPI_ENABLED:true}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGERUI_ENABLED:true}

jwt:
  secretKey: ${JWT_SECRET_KEY:library-secret}
  expirationMs: ${JWT_EXPIRATION_MS:600000}
